### ISSUE TITLE
Autocloud is unable to interpret the compose id

### ISSUE THREAD

**Issue by sayanchowdhury** [kushaldas/autocloud#53]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work
    self.consume(message)
  File "/usr/lib/python2.7/site-packages/fedimg/consumers.py", line 71, in consume
    cmetadata = fedfind.release.get_release_cid(compose_id).metadata
  File "/usr/lib/python2.7/site-packages/fedfind/release.py", line 64, in get_release_cid
    return get_release(cid=cid)
  File "/usr/lib/python2.7/site-packages/fedfind/release.py", line 380, in get_release
    (release, milestone, compose, respin) = parse_cid(cid)
  File "/usr/lib/python2.7/site-packages/fedfind/release.py", line 337, in parse_cid
    (release, date, typ, respin) = fedfind.helpers.parse_cid(cid)
  File "/usr/lib/python2.7/site-packages/fedfind/helpers.py", line 347, in parse_cid
    "compose ID!".format(origcid))
ValueError: Fedora_Docker-25-20170110.0 does not appear to be a valid Pungi 4 Fedora compose ID!

**Comment by sayanchowdhury** [comment]
This issue is because of an outdated fedfind package.

**Comment by sayanchowdhury** [comment]
This is fixed.
