### ISSUE TITLE
Traceback with new architectures

### ISSUE THREAD

**Issue by puiterwijk** [kushaldas/autocloud#55]
Autocloud should not crash when new architectures get added....

````
[Sat Mar 04 14:13:26.245350 2017] [wsgi:error] [pid 7093] ERROR:autocloud.web.app:Exception on /jobs/ [GET]
[Sat Mar 04 14:13:26.245354 2017] [wsgi:error] [pid 7093] Traceback (most recent call last):
[Sat Mar 04 14:13:26.245355 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Sat Mar 04 14:13:26.245357 2017] [wsgi:error] [pid 7093]     response = self.full_dispatch_request()
[Sat Mar 04 14:13:26.245358 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Sat Mar 04 14:13:26.245360 2017] [wsgi:error] [pid 7093]     rv = self.handle_user_exception(e)
[Sat Mar 04 14:13:26.245362 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Sat Mar 04 14:13:26.245363 2017] [wsgi:error] [pid 7093]     reraise(exc_type, exc_value, tb)
[Sat Mar 04 14:13:26.245365 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Sat Mar 04 14:13:26.245366 2017] [wsgi:error] [pid 7093]     rv = self.dispatch_request() 
[Sat Mar 04 14:13:26.245368 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Sat Mar 04 14:13:26.245369 2017] [wsgi:error] [pid 7093]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Mar 04 14:13:26.245371 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/autocloud/web/app.py", line 140, in job_details
[Sat Mar 04 14:13:26.245372 2017] [wsgi:error] [pid 7093]     request.referrer, dict(request.args)).paginate()
[Sat Mar 04 14:13:26.245374 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/autocloud/web/pagination.py", line 49, in paginate
[Sat Mar 04 14:13:26.245375 2017] [wsgi:error] [pid 7093]     page_items = self.get_ordered_page_items()
[Sat Mar 04 14:13:26.245377 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/autocloud/web/pagination.py", line 76, in get_ordered_page_items
[Sat Mar 04 14:13:26.245378 2017] [wsgi:error] [pid 7093]     items = self.queryset.all()
[Sat Mar 04 14:13:26.245380 2017] [wsgi:error] [pid 7093]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2613, in all
[Sat Mar 04 14:13:26.245381 2017] [wsgi:error] [pid 7093]     return list(self)
[Sat Mar 04 14:13:26.245382 2017] [wsgi:error] [pid 7093]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
[Sat Mar 04 14:13:26.245384 2017] [wsgi:error] [pid 7093]     util.raise_from_cause(err)
[Sat Mar 04 14:13:26.245385 2017] [wsgi:error] [pid 7093]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
[Sat Mar 04 14:13:26.245387 2017] [wsgi:error] [pid 7093]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
[Sat Mar 04 14:13:26.245388 2017] [wsgi:error] [pid 7093]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
[Sat Mar 04 14:13:26.245390 2017] [wsgi:error] [pid 7093]     rows = [proc(row) for row in fetch]
[Sat Mar 04 14:13:26.245391 2017] [wsgi:error] [pid 7093]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 428, in _instance
[Sat Mar 04 14:13:26.245396 2017] [wsgi:error] [pid 7093]     loaded_instance, populate_existing, populators)
[Sat Mar 04 14:13:26.245398 2017] [wsgi:error] [pid 7093]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full
[Sat Mar 04 14:13:26.245400 2017] [wsgi:error] [pid 7093]     dict_[key] = getter(row)
[Sat Mar 04 14:13:26.245401 2017] [wsgi:error] [pid 7093]   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 1030, in process
[Sat Mar 04 14:13:26.245403 2017] [wsgi:error] [pid 7093]     return process_value(value, dialect)
[Sat Mar 04 14:13:26.245404 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/sqlalchemy_utils/types/choice.py", line 169, in process_result_value
[Sat Mar 04 14:13:26.245406 2017] [wsgi:error] [pid 7093]     return self.type_impl.process_result_value(value, dialect)
[Sat Mar 04 14:13:26.245407 2017] [wsgi:error] [pid 7093]   File "/usr/lib/python2.7/site-packages/sqlalchemy_utils/types/choice.py", line 196, in process_result_value
[Sat Mar 04 14:13:26.245409 2017] [wsgi:error] [pid 7093]     return Choice(value, self.choices_dict[value])
[Sat Mar 04 14:13:26.245410 2017] [wsgi:error] [pid 7093] KeyError: u'aarch64'
````

**Comment by puiterwijk** [comment]
And now we crash with ppc64. We *REALLY* should not be crashing with new arches, but just ignore them.
